language: ruby
rvm:
- 2.2.5
before_install:
  - gem install bundler -v 1.17

script: ./ci-build.sh

branches:
  only:
  - master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false
